#!/usr/bin/env bash
#Bash script that Configure Nginx so that:its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow OpenSSH
sudo ufw allow Nginx HTTP
sudo ufw enable
sudo sed -i '/http {/a \ add_header X-Custom-Header "X-Served-By $hostname";' /etc/nginx/nginx.conf
sudo service nginx restart	
