#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

x=0
while [ $x -le 9 ]
do
	if [ $x -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else	
		echo "Best School"
	fi	
((x++))
done	
