#!/usr/bin/env bash
#Initiate webstack fix by installing Apache and changing root output to "Hello Holberton"
sudo apt-get -y install apache2
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
echo "ServerName localhost" > /etc/apache2/apache.conf
